### ISSUE TITLE
Internal server error for some routes

### ISSUE THREAD

**Issue by dkocich** [c2corg/v6_ui#1469]
Some routes are crashing (prod/demo/master br.) - f.e.
https://www.camptocamp.org/routes/191005/fr/el-yelmo-kindelan
https://www.camptocamp.org/routes/300430/fr/pointe-de-la-fourche-facette-ne
https://www.camptocamp.org/routes/299313/fr/trelod-arete-n

```
pyramid_mako.MakoRenderingException: 

Traceback (most recent call last):
  File "/home/dkocich/projects/c2corg/v6_ui/.build/venv/lib/python3.5/site-packages/pyramid_mako/__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File "/home/dkocich/projects/c2corg/v6_ui/.build/venv/lib/python3.5/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/home/dkocich/projects/c2corg/v6_ui/.build/venv/lib/python3.5/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/dkocich/projects/c2corg/v6_ui/.build/venv/lib/python3.5/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/dkocich/projects/c2corg/v6_ui/.build/venv/lib/python3.5/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/dkocich/projects/c2corg/v6_ui/c2corg_ui/templates/base.html", line 57, in render_body
    ${self.body()}
  File "/home/dkocich/projects/c2corg/v6_ui/c2corg_ui/templates/route/view.html", line 133, in render_body
    ${get_route_gear(route, locale)}
  File "/home/dkocich/projects/c2corg/v6_ui/c2corg_ui/templates/route/helpers/view.html", line 264, in render_get_route_gear
    <%
  File "/home/dkocich/projects/c2corg/v6_ui/c2corg_ui/templates/utils/__init__.py", line 127, in get_route_gear_articles
    articles.append('185384', 'easy mountain climbing gear')
TypeError: append() takes exactly one argument (2 given)
```

**Comment by asaunier** [comment]
Good catch, thanks :)
I have suggested a fix (untested) at #1471

**Comment by dkocich** [comment]
Thanks but maybe we can solve also this problem in one PR?

https://www.camptocamp.org/routes/111829/fr/291699
https://www.camptocamp.org//routes/107845/fr/291701

```
pyramid_mako.MakoRenderingException: 

Traceback (most recent call last):
  File "/home/dkocich/projects/c2corg/v6_ui/.build/venv/lib/python3.5/site-packages/pyramid_mako/__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File "/home/dkocich/projects/c2corg/v6_ui/.build/venv/lib/python3.5/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/home/dkocich/projects/c2corg/v6_ui/.build/venv/lib/python3.5/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/dkocich/projects/c2corg/v6_ui/.build/venv/lib/python3.5/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/dkocich/projects/c2corg/v6_ui/.build/venv/lib/python3.5/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/dkocich/projects/c2corg/v6_ui/c2corg_ui/templates/base.html", line 11, in render_body
    <html ng-cloak <%block name="pagelang"></%block> ng-app="app" ng-controller="MainController as mainCtrl">
  File "/home/dkocich/projects/c2corg/v6_ui/c2corg_ui/templates/route/view.html", line 31, in render_pagetitle
    <%block name="pagetitle"><title>${show_locale_title(locale, True)}</title></%block>
  File "/home/dkocich/projects/c2corg/v6_ui/c2corg_ui/templates/helpers/view.html", line 110, in render_show_locale_title
    <%
KeyError: 'title'
```

**Comment by asaunier** [comment]
> maybe we can solve also this problem in one PR?

Are you sure there is a connection with this other error message?
Shouldn't you open another issue (if not already done). A dedicated PR would make sense as well.

**Comment by dkocich** [comment]
Yes, we can do it separately if you want. :)

**Comment by brunobesson** [comment]
Working on demo.
