### ISSUE TITLE
Error 500 for outings containing a [video] tag

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1689]
A message error is returned when opening these outings: https://www.camptocamp.org/outings/883813/fr/verdon-l-escales-l-offre
https://www.camptocamp.org/outings/894458/fr/les-tampes-col-du-freu-et-couloir-s

According to https://forum.camptocamp.org/t/v6-vos-questions-les-reponses/173468/491?u=miko, the bug could come from the link to youtube. This sounds weird. To be clarified. The 2 outings add a link to youtube for a video.

**Comment by asaunier** [comment]
The 2 example outings contain a ``[video]`` tag such as ``[video]https://www.youtube.com/watch?v=rdgyTDAoQiY[/video]``. This tag seems to make the document viewing and previewing crash. Here is the error message found in the logs:
```
Traceback (most recent call last):
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/pyramid_debugtoolbar/toolbar.py", line 192, in toolbar_tween
    response = _handler(request)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/pyramid/viewderivers.py", line 465, in rendered_view
    request, result, view_inst, context)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/pyramid/renderers.py", line 432, in render_view
    return self.render_to_response(response, system, request=request)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/pyramid/renderers.py", line 455, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/pyramid/renderers.py", line 451, in render
    result = renderer(value, system_values)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/pyramid_mako/__init__.py", line 156, in __call__
    reraise(MakoRenderingException(errtext), None, exc_info[2])
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/pyramid/compat.py", line 147, in reraise
    raise value.with_traceback(tb)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/pyramid_mako/__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "c2corg_ui_templates_route_preview_html", line 87, in render_body
  File "c2corg_ui_templates_route____helpers_view_html", line 1027, in render_get_document_description
  File "c2corg_ui_templates_route____helpers_view_html", line 1010, in show_attr
  File "c2corg_ui_templates_route____helpers_view_html", line 463, in render_show_attr
  File "/home/alex/Desktop/v6_ui/c2corg_ui/templates/utils/__init__.py", line 35, in get_attr
    attr = parse_code(attr, md, bb) if md or bb else attr
  File "/home/alex/Desktop/v6_ui/c2corg_ui/format/__init__.py", line 61, in parse_code
    text = _get_markdown_parser().convert(text)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/markdown/__init__.py", line 375, in convert
    newRoot = treeprocessor.run(root)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/markdown/treeprocessors.py", line 295, in run
    self.__handleInline(text), child
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/markdown/treeprocessors.py", line 106, in __handleInline
    data, patternIndex, startIndex)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/markdown/treeprocessors.py", line 239, in __applyPattern
    node = pattern.handleMatch(match)
  File "/home/alex/Desktop/v6_ui/c2corg_ui/format/video.py", line 64, in handleMatch
    return self.unescape(m.group(0))
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/markdown/inlinepatterns.py", line 232, in unescape
    stash = self.markdown.treeprocessors['inline'].stashed_nodes
pyramid_mako.MakoRenderingException: 

Traceback (most recent call last):
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/pyramid_mako/__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/alex/Desktop/v6_ui/c2corg_ui/templates/route/preview.html", line 43, in render_body
    ${get_document_description(locale, 'route')}
  File "/home/alex/Desktop/v6_ui/c2corg_ui/templates/helpers/view.html", line 541, in render_get_document_description
    ${show_attr(locale, 'summary')}
  File "/home/alex/Desktop/v6_ui/c2corg_ui/templates/helpers/view.html", line 523, in show_attr
    <%def name="get_document_description(locale, doctype, title=None)">\
  File "/home/alex/Desktop/v6_ui/c2corg_ui/templates/helpers/view.html", line 53, in render_show_attr
    <%
  File "/home/alex/Desktop/v6_ui/c2corg_ui/templates/utils/__init__.py", line 35, in get_attr
    attr = parse_code(attr, md, bb) if md or bb else attr
  File "/home/alex/Desktop/v6_ui/c2corg_ui/format/__init__.py", line 61, in parse_code
    text = _get_markdown_parser().convert(text)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/markdown/__init__.py", line 375, in convert
    newRoot = treeprocessor.run(root)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/markdown/treeprocessors.py", line 295, in run
    self.__handleInline(text), child
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/markdown/treeprocessors.py", line 106, in __handleInline
    data, patternIndex, startIndex)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/markdown/treeprocessors.py", line 239, in __applyPattern
    node = pattern.handleMatch(match)
  File "/home/alex/Desktop/v6_ui/c2corg_ui/format/video.py", line 64, in handleMatch
    return self.unescape(m.group(0))
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/markdown/inlinepatterns.py", line 232, in unescape
    stash = self.markdown.treeprocessors['inline'].stashed_nodes
AttributeError: 'C2CVideo' object has no attribute 'markdown'
```

**Comment by asaunier** [comment]
Until a solution is found I have removed the ``[video]`` tag in those 2 outings so that they are at least accessible. Other outings with such a tag a most likely impacted as well.

**Comment by brunobesson** [comment]
Mmmh... Since I introduced this code, I am probably responsible for the bug. But how is it it never happened before?

I'll try to have a look...

**Comment by brunobesson** [comment]
I think I'll need some help... Because the code was working before, and isn't anymore, could this be a side effect?

Some results of me digging into it:

* to make it no fail, I need to replace https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/format/video.py#L22 with `pattern.markdown = md`. But this is different from what is done in the [img parser](https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/format/video.py). I got inspiration from it to write the code.
* Then, there is no match, because [m.group(2)](https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/format/video.py#L30) returns which is not the content of the tag, e.g. `klzzwxh:0002` (`[video]klzzwxh:0002[/video]` for m.group(0)). Is this because the point above is incorrect, or could another process modify the string first?

**Comment by desnoes** [comment]
A profile that is also impacted: https://www.camptocamp.org/profiles/6057/fr
Rozenn has many video in her profile

**Comment by asaunier** [comment]
@desnoes No surprise: the ``[video]`` tag parser is used in all documents => the problem then impacts all document containing such a tag.
