### ISSUE TITLE
Incomplete or problematic build requirement

### ISSUE THREAD

**Issue by LaurentBonnaud** [c2corg/v6_ui#437]
README.md has a list of requirements but this one has a problem:

` * Python 3.4`

because it does not specify "or higher".  Either python 3.5 is OK and it should be written down, or it is not and this is a big problem since recent/upcoming Linux distribution (Ubuntu 16.04, Debian stretch) ship python 3.5 by default.

**Comment by tsauerwein** [comment]
Python 3.4 is the Python version that we are using. But it should also work with Python 3.5, it's just that we haven't tested. Feel free to report back if you are using 3.5 so that we could adjust the requirements.

**Comment by LaurentBonnaud** [comment]
On my Ubuntu 16.04 system with Python 3.5 I could:

 - finish the build
 - launch the HTTP server
 - display the application

But running the tests gives the following error:

```
$ make -f config/dev test
.build/venv/bin/nosetests
Trying `CDLL(libgeos_c.so.1)`
Library path: 'libgeos_c.so.1'
DLL: <CDLL 'libgeos_c.so.1', handle 2e374f0 at 0x7f49e3524b00>
Trying `CDLL(libc.so.6)`
Library path: 'libc.so.6'
DLL: <CDLL 'libc.so.6', handle 7f49e5377a88 at 0x7f49e3af2e48>
......F......
======================================================================
FAIL: test_api_call (c2corg_ui.tests.views.test_route.TestRouteUi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/donnees/v6_ui/c2corg_ui/tests/views/test_route.py", line 16, in test_api_call
    self._test_api_call()
  File "/donnees/v6_ui/c2corg_ui/tests/views/__init__.py", line 39, in _test_api_call
    self.assertEqual(resp['status'], '200')
AssertionError: '500' != '200'
- 500
? ^
+ 200
? ^

-------------------- >> begin captured logging << --------------------
c2corg_ui.views.document: DEBUG: API: GET http://c2corgv6-api.demo-camptocamp.com/routes
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 13 tests in 6.960s

FAILED (failures=1)
Makefile:66: recipe for target 'test' failed
make: *** [test] Error 1

```

**Comment by LaurentBonnaud** [comment]
However, this one does not fail:

```
$ .build/venv/bin/nosetests -s
Trying `CDLL(libgeos_c.so.1)`
Library path: 'libgeos_c.so.1'
DLL: <CDLL 'libgeos_c.so.1', handle 2e50320 at 0x7f36adcd5a90>
Trying `CDLL(libc.so.6)`
Library path: 'libc.so.6'
DLL: <CDLL 'libc.so.6', handle 7f36afb29a88 at 0x7f36ab52d2e8>
.............
----------------------------------------------------------------------
Ran 13 tests in 4.973s

OK
```

**Comment by LaurentBonnaud** [comment]
Here is the last one:

```
$ make -f config/dev check
.build/venv/bin/flake8 c2corg_ui
scripts/env_replace < common.ini.in > common.ini
chmod --reference common.ini.in common.ini
sed -i 's|__CLOSURE_LIBRARY_PATH__|/donnees/v6_ui/node_modules/closure-util/.deps/library/053d4c2a9f9361da028eee5a3a9a868ca83c1c16|g' common.ini
scripts/env_replace < production.ini.in > production.ini
chmod --reference production.ini.in production.ini
sed -i 's|__CLOSURE_LIBRARY_PATH__|/donnees/v6_ui/node_modules/closure-util/.deps/library/053d4c2a9f9361da028eee5a3a9a868ca83c1c16|g' production.ini
scripts/env_replace < apache/app-c2corg_ui.wsgi.in > apache/app-c2corg_ui.wsgi
chmod --reference apache/app-c2corg_ui.wsgi.in apache/app-c2corg_ui.wsgi
sed -i 's|__CLOSURE_LIBRARY_PATH__|/donnees/v6_ui/node_modules/closure-util/.deps/library/053d4c2a9f9361da028eee5a3a9a868ca83c1c16|g' apache/app-c2corg_ui.wsgi
scripts/env_replace < apache/wsgi.conf.in > apache/wsgi.conf
chmod --reference apache/wsgi.conf.in apache/wsgi.conf
sed -i 's|__CLOSURE_LIBRARY_PATH__|/donnees/v6_ui/node_modules/closure-util/.deps/library/053d4c2a9f9361da028eee5a3a9a868ca83c1c16|g' apache/wsgi.conf
scripts/env_replace < test.ini.in > test.ini
chmod --reference test.ini.in test.ini
sed -i 's|__CLOSURE_LIBRARY_PATH__|/donnees/v6_ui/node_modules/closure-util/.deps/library/053d4c2a9f9361da028eee5a3a9a868ca83c1c16|g' test.ini
scripts/env_replace < MANIFEST.in > MANIFEST
chmod --reference MANIFEST.in MANIFEST
sed -i 's|__CLOSURE_LIBRARY_PATH__|/donnees/v6_ui/node_modules/closure-util/.deps/library/053d4c2a9f9361da028eee5a3a9a868ca83c1c16|g' MANIFEST
scripts/env_replace < development.ini.in > development.ini
chmod --reference development.ini.in development.ini
sed -i 's|__CLOSURE_LIBRARY_PATH__|/donnees/v6_ui/node_modules/closure-util/.deps/library/053d4c2a9f9361da028eee5a3a9a868ca83c1c16|g' development.ini
.build/venv/bin/nosetests
Trying `CDLL(libgeos_c.so.1)`
Library path: 'libgeos_c.so.1'
DLL: <CDLL 'libgeos_c.so.1', handle 1872c70 at 0x7f0a30df9080>
Trying `CDLL(libc.so.6)`
Library path: 'libc.so.6'
DLL: <CDLL 'libc.so.6', handle 7f0a30f13a88 at 0x7f0a2e218198>
.............
----------------------------------------------------------------------
Ran 13 tests in 4.394s

OK
```

**Comment by LaurentBonnaud** [comment]
The AssertionError disappeared after I updated my local copy of the repository.
Everything seems to be working OK.
Which percentage of the code do the tests cover ?

**Comment by tsauerwein** [comment]
> The AssertionError disappeared after I updated my local copy of the repository.
> Everything seems to be working OK.

Thanks for testing! Do you want to create a PR to update the requirements in the readme?

> Which percentage of the code do the tests cover ?

The tests for the UI are pretty basic (unfortunately), but the API should have a relatively solid coverage.

**Comment by LaurentBonnaud** [comment]
> Do you want to create a PR to update the requirements in the readme?

That was already the goal of this bug report.
