### ISSUE TITLE
Angular error in outing pages

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#495]
In the demo, when loading an outing page I get the following JS error in the console, whether I am logged in or not:

> angular.js:13708Error: [$parse:ueoe] http://errors.angularjs.org/1.5.7/$parse/ueoe?p0=userCtrl.hasEditRights(%5B%7B
    at Error (native)
    at http://c2corgv6.demo-camptocamp.com/node_modules//angular/angular.min.js:6:412
    at Object.t.peekToken (http://c2corgv6.demo-camptocamp.com/node_modules//angular/angular.min.js:229:227)
    at Object.t.object (http://c2corgv6.demo-camptocamp.com/node_modules//angular/angular.min.js:227:322)
    at Object.t.primary (http://c2corgv6.demo-camptocamp.com/node_modules//angular/angular.min.js:224:388)
    at Object.t.unary (http://c2corgv6.demo-camptocamp.com/node_modules//angular/angular.min.js:224:227)
    at Object.t.multiplicative (http://c2corgv6.demo-camptocamp.com/node_modules//angular/angular.min.js:223:475)
    at Object.t.additive (http://c2corgv6.demo-camptocamp.com/node_modules//angular/angular.min.js:223:302)
    at Object.t.relational (http://c2corgv6.demo-camptocamp.com/node_modules//angular/angular.min.js:223:137)
    at Object.t.equality (http://c2corgv6.demo-camptocamp.com/node_modules//angular/angular.min.js:222:465)

**Comment by asaunier** [comment]
If this issue has been fixed by a merged PR, please add a reference to this PR.

**Comment by ginold** [comment]
fixed in #outing
