### ISSUE TITLE
display new route in the  advanced research page

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#522]
I have just created a new route (http://c2corgv6.demo-camptocamp.com/routes/736995/en) and it is not displayed in the advanced research page ('topoguide').

**Comment by asaunier** [comment]
Is the problem still valid? The Elastic Search sync script was down, I have relaunched it yesterday afternoon. Have you tried to recreate a route recently? @shortoland seems to say it worked for him!?

Is the problem limited to routes? Or do you observe it for waypoints and outings as well?

**Comment by stef74** [comment]
@shortoland pleas test and confirm the status of this issue

**Comment by asaunier** [comment]
Mmm, one of the sync scripts was down again with the following stack:
> ...
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2693, in one
    ret = list(self)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 182, in reraise
    raise value.with_traceback(tb)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (psycopg2.DatabaseError) SSL SYSCALL error: EOF detected
 [SQL: 'SELECT guidebook.es_sync_status.last_update AS guidebook_es_sync_status_last_update, now() AS date_now \nFROM guidebook.es_sync_status \nWHERE guidebook.es_sync_status.id = %(id_1)s'] [parameters: {'id_1': 1}]
Makefile:70: recipe for target 'run-syncer-prod' failed
make: *** [run-syncer-prod] Killed

The other was probably also interrupted:

> sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL SYSCALL error: EOF detected
 [SQL: 'DELETE FROM users.token WHERE users.token.expire <= %(expire_1)s'] [parameters: {'expire_1': datetime.datetime(2016, 7, 23, 22, 30, 0, 153297)}]
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/__init__.py", line 978, in emit
    msg = self.format(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 828, in format
    return fmt.format(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 573, in format
    record.exc_text = self.formatException(record.exc_info)
  File "/usr/lib/python3.4/logging/__init__.py", line 523, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
  File "/usr/lib/python3.4/traceback.py", line 169, in print_exception
    for line in _format_exception_iter(etype, value, tb, limit, chain):
  File "/usr/lib/python3.4/traceback.py", line 146, in _format_exception_iter
    for value, tb in values:
  File "/usr/lib/python3.4/traceback.py", line 125, in _iter_chain
    context = exc.__context__
AttributeError: 'NoneType' object has no attribute '__context__'
Call stack:
  File "/usr/lib/python3.4/threading.py", line 888, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 65, in _worker
    work_item.run()
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 58, in run
    self.future.set_result(result)
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 491, in set_result
    self._invoke_callbacks()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/apscheduler/executors/pool.py", line 20, in callback
    self._run_job_success(job.id, f.result())
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/apscheduler/executors/base.py", line 90, in _run_job_success  
    self._scheduler._dispatch_event(event)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/apscheduler/schedulers/base.py", line 765, in _dispatch_event 
    cb(event)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/jobs/__init__.py", line 13, in exception_listener
    log.exception('The job crashed')
Message: 'The job crashed'

I have restarted both scripts.

@tsauerwein any clue what happened?

**Comment by tsauerwein** [comment]
It looks like the connection to the database was closed, I opened a ticket for it: https://github.com/c2corg/v6_api/issues/344

**Comment by stef74** [comment]
I remove label fixed please readd it when i'ts ready.

**Comment by asaunier** [comment]
> I remove label fixed please readd it when i'ts ready.

I think this sync script error should not be considered with the current issue since it's an API problem with  a dedicated issue https://github.com/c2corg/v6_api/issues/344

Currently the sync script is running as expected, could you test that the newly created waypoints/routes/outings actually appear in the advanced search page?

**Comment by stef74** [comment]
@desnoes @shortoland please test

**Comment by shortoland** [comment]
It's OK, but it seems I have to reach then reload the topoguide page in order to update the list (same with outings or WP)

@desnoes do you confirm ?

**Comment by stef74** [comment]
I confirm
