### ISSUE TITLE
Problem with document detail view cache?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#570]
Now and then I have observed 500 errors when loading a document detail view page, with the following stack

```
ValueError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last)
File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
￼￼result = handler(request)
File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 62, in excview_tween
￼￼reraise(*attrs['exc_info'])
File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/compat.py", line 148, in reraise
￼￼raise value
File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 22, in excview_tween
￼￼response = handler(request)
File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 158, in handle_request
￼￼view_name
File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/view.py", line 547, in _call_view
￼￼response = view_callable(context, request)
File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 413, in viewresult_to_response
￼￼result = view(context, request)
File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 123, in _class_requestonly_view
￼￼response = getattr(inst, attr)()
File "/home/alex/Desktop/v6_ui/c2corg_ui/views/waypoint.py", line 59, in detail
￼￼return self._get_or_create_detail(id, lang, render_page)
File "/home/alex/Desktop/v6_ui/c2corg_ui/views/document.py", line 83, in _get_or_create_detail
￼￼self._get_cache_key)
File "/home/alex/Desktop/v6_ui/c2corg_ui/views/document.py", line 119, in _get_or_create
￼￼not_modified, api_cache_key, loaded_data = load_data(old_api_cache_key)
File "/home/alex/Desktop/v6_ui/c2corg_ui/views/document.py", line 78, in load_data
￼￼self._get_document(id, lang, old_api_cache_key)
File "/home/alex/Desktop/v6_ui/c2corg_ui/views/document.py", line 190, in _get_document
￼￼url, old_api_cache_key)
File "/home/alex/Desktop/v6_ui/c2corg_ui/views/document.py", line 226, in _get_with_etag
￼￼resp, document = self._call_api(url, headers)
File "/home/alex/Desktop/v6_ui/c2corg_ui/views/document.py", line 161, in _call_api
￼￼return resp, resp.json()
File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/requests/models.py", line 733, in json
￼￼return json.loads(self.text, **kwargs)
File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
￼￼return _default_decoder.decode(s)
File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
￼￼obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
￼￼raise ValueError(errmsg("Expecting value", s, err.value)) from None
```

If the page is reloaded, it is displayed as expected.

**Comment by tsauerwein** [comment]
Do you see errors in the API log?

**Comment by asaunier** [comment]
At the same time I see in the API logs a stack ending with
> redis.exceptions.LockError: Cannot release a lock that's no longer owned

**Comment by tsauerwein** [comment]
That's the error @arnaud-morvan noticed: https://github.com/c2corg/v6_api/issues/368

Did you also maybe work with the debugger on the API?

**Comment by asaunier** [comment]
I don't know but since the debugger is available in my dev UI and since both my dev UI and dev API works in dev mode, I guess it's on in my API as well.

**Comment by tsauerwein** [comment]
I mean did you use the debugger, e.g. set a breakpoint, step through the code, ...?

**Comment by arnaud-morvan** [comment]
As this is an API issue, I propose to close this and use c2corg/v6_api#368 instead.

**Comment by asaunier** [comment]
> I mean did you use the debugger, e.g. set a breakpoint, step through the code, ...?

No

> As this is an API issue, I propose to close this and use c2corg/v6_api#368 instead.

Since this impacts the UI (ie. the UI crashes), I would prefer we keep this issue open until c2corg/v6_api#368  is fixed.

**Comment by arnaud-morvan** [comment]
Maybe we should improve API request error handling on UI side ? Is API returning status=500 ?

**Comment by tsauerwein** [comment]
> Maybe we should improve API request error handling on UI side ? Is API returning status=500 ?

I agree that the error message should be clearer. See also https://github.com/c2corg/v6_ui/issues/27
