### ISSUE TITLE
Crash of some outing detail view pages

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#752]
Perhaps it's something misconfigured on the dev server or the demo instance:

http://c2corgv6.demo-camptocamp.com/outings/736779/fr/pic-saint-michel-versant-e-par-le-col-de-l-arc => 500 error

logs:

> [Wed Oct 19 13:51:51.875982 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366] mod_wsgi (pid=3892): Exception occurred processing WSGI script '/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/apache/app-c2corg_ui.wsgi'.
[Wed Oct 19 13:51:51.882228 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366] Traceback (most recent call last):
[Wed Oct 19 13:51:51.891054 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 236, in __call__
[Wed Oct 19 13:51:51.891117 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     response = self.invoke_subrequest(request, use_tweens=True)
[Wed Oct 19 13:51:51.891228 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 211, in invoke_subrequest
[Wed Oct 19 13:51:51.891246 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     response = handle_request(request)
[Wed Oct 19 13:51:51.907618 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/caching/cacheversion.py", line 43, in __call__
[Wed Oct 19 13:51:51.907696 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     return self.handler(request)
[Wed Oct 19 13:51:51.907859 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 62, in excview_tween
[Wed Oct 19 13:51:51.907888 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     reraise(*attrs['exc_info'])
[Wed Oct 19 13:51:51.907991 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/compat.py", line 148, in reraise
[Wed Oct 19 13:51:51.908018 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     raise value
[Wed Oct 19 13:51:51.908091 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 22, in excview_tween
[Wed Oct 19 13:51:51.908110 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     response = handler(request)
[Wed Oct 19 13:51:51.908183 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 158, in handle_request
[Wed Oct 19 13:51:51.908208 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     view_name
[Wed Oct 19 13:51:51.908314 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/view.py", line 547, in _call_view
[Wed Oct 19 13:51:51.908342 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     response = view_callable(context, request)
[Wed Oct 19 13:51:51.908460 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 413, in viewresult_to_response
[Wed Oct 19 13:51:51.908536 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     result = view(context, request)
[Wed Oct 19 13:51:51.908620 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 123, in _class_requestonly_view
[Wed Oct 19 13:51:51.908646 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     response = getattr(inst, attr)()
[Wed Oct 19 13:51:51.925752 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/outing.py", line 52, in detail
[Wed Oct 19 13:51:51.925807 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     return self._get_or_create_detail(id, lang, render_page)
[Wed Oct 19 13:51:51.925966 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/document.py", line 85, in _get_or_create_detail
[Wed Oct 19 13:51:51.925992 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     self._get_cache_key)
[Wed Oct 19 13:51:51.926058 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/document.py", line 121, in _get_or_create
[Wed Oct 19 13:51:51.926074 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     not_modified, api_cache_key, loaded_data = load_data(old_api_cache_key)
[Wed Oct 19 13:51:51.926174 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/document.py", line 80, in load_data
[Wed Oct 19 13:51:51.926216 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     self._get_document(id, lang, old_api_cache_key)
[Wed Oct 19 13:51:51.926283 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/document.py", line 192, in _get_document
[Wed Oct 19 13:51:51.926305 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     url, old_api_cache_key)
[Wed Oct 19 13:51:51.926392 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/document.py", line 236, in _get_with_etag
[Wed Oct 19 13:51:51.926436 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     resp, document = self._call_api(url, headers)
[Wed Oct 19 13:51:51.926502 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/document.py", line 163, in _call_api
[Wed Oct 19 13:51:51.926525 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     return resp, resp.json()
[Wed Oct 19 13:51:51.943242 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/requests/models.py", line 733, in json
[Wed Oct 19 13:51:51.943316 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     return json.loads(self.text, **kwargs)
[Wed Oct 19 13:51:51.943446 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
[Wed Oct 19 13:51:51.943482 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     return _default_decoder.decode(s)
[Wed Oct 19 13:51:51.943558 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
[Wed Oct 19 13:51:51.943577 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[Wed Oct 19 13:51:51.943656 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]   File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
[Wed Oct 19 13:51:51.943707 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366]     raise ValueError(errmsg("Expecting value", s, err.value)) from None
[Wed Oct 19 13:51:51.943810 2016] [wsgi:error] [pid 3892] [remote 10.27.71.4:63366] ValueError: Expecting value: line 1 column 1 (char 0)

**Comment by asaunier** [comment]
After updating the DB+UI+API this problem seems no longer reproducible.
