### ISSUE TITLE
Not able to  create new article?

### ISSUE THREAD

**Issue by dkocich** [c2corg/v6_ui#839]
I can not create a new article (but I can edit it without a problem...).
http://c2corgv6.demo-camptocamp.com/articles/add

I get just a red box with "Failed saving the changes" and internal server error.

![image](https://cloud.githubusercontent.com/assets/6165660/19971354/0a47f838-a1df-11e6-967f-24e4a93678fb.png)

Automated tests on localhost are ok and I did not have this problem before. I am not sure if this was here also before or something was changed lately so it does not work now...

When I look into the server console log (localhost) I see a duplicate key error in documents_pkey... New insert is trying "overwrite" already existing primary keys of other documents?...

Did someone notice this problem before? @asaunier @tsauerwein

```
serving on http://0.0.0.0:6548
2016-11-03 16:11:22,042 DEBUG [c2corg_api][waitress] debug_authorization of url http://localhost:6548/articles (view name '' against context <c2corg_api.RootFactory object at 0x7fb89cceba58>): Allowed (NO_PERMISSION_REQUIRED)
2016-11-03 16:11:23,045 INFO  [sqlalchemy.engine.base.Engine][waitress] select version()
2016-11-03 16:11:23,045 INFO  [sqlalchemy.engine.base.Engine][waitress] {}
2016-11-03 16:11:23,049 INFO  [sqlalchemy.engine.base.Engine][waitress] select current_schema()
2016-11-03 16:11:23,049 INFO  [sqlalchemy.engine.base.Engine][waitress] {}
2016-11-03 16:11:23,051 INFO  [sqlalchemy.engine.base.Engine][waitress] SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2016-11-03 16:11:23,051 INFO  [sqlalchemy.engine.base.Engine][waitress] {}
2016-11-03 16:11:23,053 INFO  [sqlalchemy.engine.base.Engine][waitress] SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2016-11-03 16:11:23,053 INFO  [sqlalchemy.engine.base.Engine][waitress] {}
2016-11-03 16:11:23,054 INFO  [sqlalchemy.engine.base.Engine][waitress] show standard_conforming_strings
2016-11-03 16:11:23,054 INFO  [sqlalchemy.engine.base.Engine][waitress] {}
2016-11-03 16:11:23,057 INFO  [sqlalchemy.engine.base.Engine][waitress] BEGIN (implicit)
2016-11-03 16:11:23,059 INFO  [sqlalchemy.engine.base.Engine][waitress] SELECT count(*) AS count_1 
FROM (SELECT users.token.value AS users_token_value, users.token.expire AS users_token_expire, users.token.userid AS users_token_userid 
FROM users.token 
WHERE users.token.value = %(value_1)s AND users.token.expire > %(expire_1)s) AS anon_1
2016-11-03 16:11:23,059 INFO  [sqlalchemy.engine.base.Engine][waitress] {'expire_1': datetime.datetime(2016, 11, 3, 15, 11, 22, 991954), 'value_1': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgxMTg0OSwidXNlcm5hbWUiOiJka29jaWNoIiwiZXhwIjoxNDc5Mzk1MjMxfQ.RyJfxKgKYBJQ47SnJK3zCBN8rNq9MwsSsAHNHKpk104'}
2016-11-03 16:11:23,070 INFO  [sqlalchemy.engine.base.Engine][waitress] ROLLBACK
2016-11-03 16:11:23,080 INFO  [sqlalchemy.engine.base.Engine][waitress] BEGIN (implicit)
2016-11-03 16:11:23,082 INFO  [sqlalchemy.engine.base.Engine][waitress] SELECT count(*) AS count_1 
FROM (SELECT users."user".password AS users_user_password, users."user".id AS users_user_id, users."user".username AS users_user_username, users."user".name AS users_user_name, users."user".forum_username AS users_user_forum_username, users."user".email AS users_user_email, users."user".email_validated AS users_user_email_validated, users."user".email_to_validate AS users_user_email_to_validate, users."user".moderator AS users_user_moderator, users."user".validation_nonce AS users_user_validation_nonce, users."user".validation_nonce_expire AS users_user_validation_nonce_expire, users."user".last_modified AS users_user_last_modified, users."user".lang AS users_user_lang, users."user".is_profile_public AS users_user_is_profile_public, users."user".feed_filter_activities AS users_user_feed_filter_activities, users."user".feed_followed_only AS users_user_feed_followed_only 
FROM users."user" 
WHERE users."user".id = %(id_1)s AND users."user".moderator) AS anon_1
2016-11-03 16:11:23,082 INFO  [sqlalchemy.engine.base.Engine][waitress] {'id_1': 811849}
2016-11-03 16:11:23,085 DEBUG [c2corg_api][waitress] debug_authorization of url http://localhost:6548/articles (view name '' against context <c2corg_api.RootFactory object at 0x7fb89f033358>): ACLAllowed permission 'authenticated' via ACE ('Allow', 'system.Authenticated', 'authenticated') in ACL [('Allow', 'system.Everyone', 'public'), ('Allow', 'system.Authenticated', 'authenticated'), ('Allow', 'group:moderators', 'moderator')] on context <c2corg_api.RootFactory object at 0x7fb89f033358> for principals [811849, 'system.Everyone', 'system.Authenticated', 'system.Authenticated']
2016-11-03 16:11:23,094 INFO  [sqlalchemy.engine.base.Engine][waitress] SELECT count(*) AS count_1 
FROM (SELECT users."user".password AS users_user_password, users."user".id AS users_user_id, users."user".username AS users_user_username, users."user".name AS users_user_name, users."user".forum_username AS users_user_forum_username, users."user".email AS users_user_email, users."user".email_validated AS users_user_email_validated, users."user".email_to_validate AS users_user_email_to_validate, users."user".moderator AS users_user_moderator, users."user".validation_nonce AS users_user_validation_nonce, users."user".validation_nonce_expire AS users_user_validation_nonce_expire, users."user".last_modified AS users_user_last_modified, users."user".lang AS users_user_lang, users."user".is_profile_public AS users_user_is_profile_public, users."user".feed_filter_activities AS users_user_feed_filter_activities, users."user".feed_followed_only AS users_user_feed_followed_only 
FROM users."user" 
WHERE users."user".id = %(id_1)s AND users."user".moderator) AS anon_1
2016-11-03 16:11:23,094 INFO  [sqlalchemy.engine.base.Engine][waitress] {'id_1': 811849}
2016-11-03 16:11:23,125 INFO  [sqlalchemy.engine.base.Engine][waitress] SELECT count(*) AS count_1 
FROM (SELECT users."user".password AS users_user_password, users."user".id AS users_user_id, users."user".username AS users_user_username, users."user".name AS users_user_name, users."user".forum_username AS users_user_forum_username, users."user".email AS users_user_email, users."user".email_validated AS users_user_email_validated, users."user".email_to_validate AS users_user_email_to_validate, users."user".moderator AS users_user_moderator, users."user".validation_nonce AS users_user_validation_nonce, users."user".validation_nonce_expire AS users_user_validation_nonce_expire, users."user".last_modified AS users_user_last_modified, users."user".lang AS users_user_lang, users."user".is_profile_public AS users_user_is_profile_public, users."user".feed_filter_activities AS users_user_feed_filter_activities, users."user".feed_followed_only AS users_user_feed_followed_only 
FROM users."user" 
WHERE users."user".id = %(id_1)s AND users."user".moderator) AS anon_1
2016-11-03 16:11:23,125 INFO  [sqlalchemy.engine.base.Engine][waitress] {'id_1': 811849}
2016-11-03 16:11:23,130 INFO  [sqlalchemy.engine.base.Engine][waitress] INSERT INTO guidebook.documents (version, protected, quality, type, redirects_to) VALUES (%(version)s, %(protected)s, %(quality)s, %(type)s, %(redirects_to)s) RETURNING guidebook.documents.document_id
2016-11-03 16:11:23,130 INFO  [sqlalchemy.engine.base.Engine][waitress] {'type': 'c', 'version': 1, 'protected': None, 'redirects_to': None, 'quality': 'medium'}
2016-11-03 16:11:23,132 INFO  [sqlalchemy.engine.base.Engine][waitress] ROLLBACK
2016-11-03 16:11:23,135 DEBUG [c2corg_api][waitress] debug_authorization of url http://localhost:6548/articles (view name '' against context IntegrityError('(psycopg2.IntegrityError) duplicate key value violates unique constraint "documents_pkey"\nDETAIL:  Key (document_id)=(2) already exists.\n',)): Allowed (NO_PERMISSION_REQUIRED)
2016-11-03 16:11:23,145 ERROR [pyramid_debugtoolbar][waitress] Exception at http://localhost:6548/articles
traceback url: http://localhost:6548/_debug_toolbar/exception?token=6227335c7862636b5c7863315c7831315c7861325c7865625c783933606827&tb=140430667972960
Traceback (most recent call last):
  File "/home/dkocich/projects/c2corg/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/dkocich/projects/c2corg/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: duplicate key value violates unique constraint "documents_pkey"
DETAIL:  Key (document_id)=(2) already exists.
```

**Comment by tsauerwein** [comment]
Can you check the current value of the sequence `guidebook.documents_document_id_seq`?

The sequence should be updated in the migration script: https://github.com/c2corg/v6_api/blob/master/c2corg_api/scripts/migration/sequences.py

**Comment by dkocich** [comment]
Looks ok in my DB.

![image](https://cloud.githubusercontent.com/assets/6165660/19973646/1b446750-a1e6-11e6-8e98-24d949e73e6e.png)

**Comment by dkocich** [comment]
When I try to create more articles, I just get the error with higher ID - like it do not see last value of the sequence...?

**Comment by tsauerwein** [comment]
In your database, is the column `document_id` configured to use the sequence?

```
                                                                Table "guidebook.documents"
    Column    |          Type          |                                 Modifiers                                 | Storage  | Stats target | Description 
--------------+------------------------+---------------------------------------------------------------------------+----------+--------------+-------------
 version      | integer                | not null default 1                                                        | plain    |              | 
 protected    | boolean                |                                                                           | plain    |              | 
 quality      | guidebook.quality_type | not null default 'draft'::guidebook.quality_type                          | plain    |              | 
 type         | character varying(1)   |                                                                           | extended |              | 
 document_id  | integer                | not null default nextval('guidebook.documents_document_id_seq'::regclass) | plain    |              | 
```

**Comment by asaunier** [comment]
When testing with my own UI/API I get a sligthly different stracktrace:

> (...)
  File "/home/alex/v6_api/c2corg_api/views/article.py", line 47, in collection_post
    return self._collection_post(schema_article)
  File "/home/alex/v6_api/c2corg_api/views/document.py", line 174, in _collection_post
    document_in, schema, before_add, after_add)
  File "/home/alex/v6_api/c2corg_api/views/document.py", line 204, in _create_document
    added_associations, [], document.document_id)
  File "/home/alex/v6_api/c2corg_api/models/cache_version.py", line 376, in update_cache_version_associations
    documents_to_update.remove(ignore_document_id)
KeyError: 813303

**Comment by asaunier** [comment]
Looks like an API issue. Not related to the UI, is it?

Then could you move this issue to the API repo (ie. create an API issue, link to this issue, copy useful data) and close this issue?
